name: p2prc # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: p2p network designed for computation # 79 char long summary
description: |
  This project aims to create a peer to peer (p2p) network, where a user can use the p2p network to act as a client (i.e sending tasks) or the server (i.e executing the tasks). A prototype application will be developed, which comes bundled with a p2p module and possible to execute docker containers or virtual environments across selected nodes.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  p2prc:
    command: p2prc

parts:
  p2prc:
    source: '.'
    source-tag: master
    plugin: go
    # keep me up to date with the go version that go-ipfs expects to be built with.
    go-channel: 1.15/stable
    go-importpath: https://github.com/Akilan1999/p2p-rendering-computation
    build-packages:
      - build-essential
    # use `make` to build and set the snap version from `ipfs version` output
    override-build: |
      export GOPATH=$SNAPCRAFT_PART_BUILD/go
      make build
      cp $SNAPCRAFT_PART_BUILD/go/bin/p2prc $SNAPCRAFT_PART_INSTALL
      export P2PRC_VERSION=$($SNAPCRAFT_PART_BUILD/go/bin/p2prc version --commit | cut -c 14-)
      export P2PRC=
      echo "found version $P2PRC_VERSION"
      snapcraftctl set-version $P2PRC_VERSION

